<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php
$collapsible = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('wokiee_settings/sidebar/layered_collapsible');
$opened = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('wokiee_settings/sidebar/layered_opened');
if ($collapsible) {
    $c_class = ' collapsible';
} else {
    $c_class = '';
}
if ($collapsible && $opened) {
    $o_class = ' open';
} else {
    $o_class = '';
}
?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?= /* @escapeNotVerified */ __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= /* @escapeNotVerified */ __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>

            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <dl class="filter-options<?= $c_class.$o_class; ?>">
                        <dt class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                    </dl>
                <?php endif; ?>
            <?php endforeach; ?>

        </div>
    </div>
<?php endif; ?>
