<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>


<?php
$list_conf = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('wokiee_settings/product_listing');
$isQuick = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('weltpixel_quickview/general/enable_product_listing');
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="top-toolbar">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $image_hover = 'category_page_grid_hover';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $image_hover = 'category_page_grid_hover';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();

    $get_category = $this->helper('Ecomwares\Wokiee\Helper\Data')->getCurrentCategory();

    if ($get_category) {
        if($get_category == '1column') {
            $column_layout = ' col-6 col-md-4 col-lg-3 tt-col-item';
        } else {
            $column_layout = ' col-6 col-md-4 tt-col-item';
        }
    } else {
        if($block->getLayout()->getUpdate()->getPageLayout() == '1column') {
            $column_layout = ' col-6 col-md-4 col-lg-3 tt-col-item';
        } else {
            $column_layout = ' col-6 col-md-4 tt-col-item';
        }
    }

    ?>

    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <div class="tt-product-listing row products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<div class="item product product-item'.$column_layout.'">' : '</div><div class="item product product-item'.$column_layout.'">' ?>
                <div class="tt-product thumbprod-center product-item-info" data-container="product-grid">
                    <div class="tt-image-box">
                        <?php $productUrl = $this->getUrl('weltpixel_quickview/catalog_product/view', array('id' => $_product->getId())); ?>
                        <?php if ($list_conf['list_quick'] && $isQuick): ?>
                        <a href="javascript:void(0);" data-quickview-url="<?= $productUrl; ?>" class="weltpixel-quickview tt-btn-quickview"></a>
                        <?php endif; ?>
                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $list_conf['list_wishlist']): ?>
                            <a href="#"
                               class="action towishlist"
                               title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                               aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                               data-action="add-to-wishlist"
                               role="button"></a>
                        <?php endif; ?>
                        <?php if ($list_conf['list_compare']): ?>
                        <?php /* @escapeNotVerified */ $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                        <a href="#"
                           class="action tocompare"
                           title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                           aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                           role="button"></a>
                        <?php endif; ?>

                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php
                                $productImage = $_imagehelper->init($_product, $image);
                                $productImageUrl = $productImage->getUrl();
                                $productHoverImage = $_imagehelper->init($_product, $image_hover);
                                $productHoverImageUrl = $productHoverImage->getUrl();
                                $img_ratio = round(($_imagehelper->getHeight() / $_imagehelper->getWidth())*100);
                            ?>
                            <span class="tt-img product-image-container" style="width:<?= /* @escapeNotVerified */ $_imagehelper->getWidth() ?>px;">
                                <span class="product-image-wrapper" style="padding-bottom: <?= /* @escapeNotVerified */ $img_ratio; ?>%;">
                                    <img class="product-image-photo" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                </span>
                            </span>
                            <?php if ($list_conf['list_hover']): ?>
                                <?php if($productImageUrl != str_replace("/img_hover/","/small_image/",$productHoverImageUrl)): ?>
                                    <span class="tt-img-roll-over product-image-container" style="width:<?= /* @escapeNotVerified */ $_imagehelper->getWidth() ?>px;">
                                        <span class="product-image-wrapper" style="padding-bottom: <?= /* @escapeNotVerified */ $img_ratio; ?>%;">
                                            <img class="product-image-photo-hover" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                        </span>
                                    </span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </a>

                        <span class="tt-label-location">
                            <?php if ($list_conf['list_label']): ?>
                            <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->newLabel($_product); ?>
                            <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->saleLabel($_product); ?>
                            <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->featuredLabel($_product); ?>
                            <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->getBestsellers($_product); ?>
                            <?php endif; ?>
                            <?php if (!$_product->isSaleable()): ?>
                                <?php if ($_product->isAvailable()): ?>
                                    <span class="tt-label-out-stock"><?= /* @escapeNotVerified */ __('In stock') ?></span>
                                <?php else: ?>
                                    <span class="tt-label-out-stock"><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </span>
                        <?php
                            if ($list_conf['list_countdown']):
                                echo $this->helper('Ecomwares\Wokiee\Helper\Data')->getCountdown($_product);
                            endif;
                        ?>
                    </div>
                    <div class="tt-description product details product-item-details">
                        <div class="tt-row">
                            <?php if ($_product->getAttributeText('manufacturer') && $list_conf['list_brands']): ?>
                            <ul class="tt-add-info">
                                <li><?php echo $_product->getAttributeText('manufacturer') ?></li>
                            </ul>
                            <?php endif; ?>
                            <?php if ($list_conf['list_rating']): ?>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php endif; ?>
                        </div>
                        <h2 class="tt-title">
                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                        </h2>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <div class="tt-text-info">
                            <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        </div>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="tt-product-inside-hover product actions product-item-actions">
                            <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                            class="tt-btn-addtocart thumbprod-button-bg action tocart primary">
                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            <?php endif; ?>
                            <div class="addto_btns">
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $list_conf['list_wishlist']): ?>
                                    <a href="#"
                                       class="action towishlist"
                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button"></a>
                                <?php endif; ?>
                                <?php if ($list_conf['list_compare']): ?>
                                <?php /* @escapeNotVerified */ $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                <a href="#"
                                   class="action tocompare"
                                   title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                   aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                   role="button"></a>
                                <?php endif; ?>
                                <?php if ($list_conf['list_quick'] && $isQuick): ?>
                                    <a href="javascript:void(0);" data-quickview-url="<?= $productUrl; ?>" class="weltpixel-quickview tt-btn-quickview"></a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="bottom-toolbar">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>

<?php endif; ?>
