<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar search form template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Search
 */
?>

<div class="widget block blog-search" data-bind="scope: 'blog-search'">
    <div class="block-title">
        <strong><?php echo __('Search') ?></strong>
    </div>
    <div class="block-content">
		<form class="form form-default" id="blog_search_mini_form" action="<?php echo $block->getFormUrl() ?>" method="get">
            <div class="tt-form-search">
                <input id="blog_search" type="text" name="q" value="<?php echo $block->escapeHtml($block->getQuery()) ?>" placeholder="<?php echo __('Search posts here...') ?>" class="input-text form-control" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">
                <button type="submit" class="tt-btn-icon icon-f-85" onclick="return goBlogSearch(this);" title="<?php echo __('Search') ?>"></button>
            </div>
        </form>
	</div>
</div>
<script type="text/javascript">
	function goBlogSearch(e)
	{
		var value = document.getElementById('blog_search').value;
		if (value) {
			window.location = e.form.action + encodeURI(value) + '/';
		}
		return false;
	}
</script>