<?php
/* comment */
use Magento\Framework\App\Action\Action;
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$image = 'category_page_grid';
$image_hover = 'category_page_grid_hover';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$tm_helper = $this->helper('Ecomwares\Wokiee\Helper\Data');

$list_conf = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('wokiee_settings/product_listing');
$isQuick = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('weltpixel_quickview/general/enable_product_listing');

if($block->getCols()) {
    $col_num = ' data-item="'.$block->getCols().'"';
} else {
    $col_num = '';
}
?>

<?php if (!$_productCollection->count()): ?>

    <div class="container-indent">
        <div class="container container-fluid-custom-mobile-padding">
            <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
        </div>
    </div>

<?php else: ?>

    <div class="tt-carousel-products row arrow-location-tab tt-alignment-img tt-layout-product-item slick-animated-show-js" <?= $col_num; ?>>
        <?php $i=0; ?>
        <?php foreach ($_productCollection as $_product): ?>
            <?php $i++; if ($i > $block->getLimit()) break; ?>
            <div class="col-2 col-md-4 col-lg-3">
                <div class="tt-product thumbprod-center">
                    <div class="tt-image-box">
                        <?php $productUrl = $this->getUrl('weltpixel_quickview/catalog_product/view', array('id' => $_product->getId())); ?>
                        <?php if ($list_conf['list_quick'] && $isQuick): ?>
                            <a href="javascript:void(0);" data-quickview-url="<?= $productUrl; ?>" class="weltpixel-quickview tt-btn-quickview"></a>
                        <?php endif; ?>
                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $list_conf['list_wishlist']): ?>
                            <a href="#"
                               class="action towishlist"
                               title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                               aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                               data-action="add-to-wishlist"
                               role="button"></a>
                        <?php endif; ?>
                        <?php if ($list_conf['list_compare']): ?>
                            <?php /* @escapeNotVerified */ $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                            <a href="#"
                               class="action tocompare"
                               title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                               aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                               role="button"></a>
                        <?php endif; ?>

                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php
                            $productImage = $_imagehelper->init($_product, $image);
                            $productImageUrl = $productImage->getUrl();
                            $productHoverImage = $_imagehelper->init($_product, $image_hover);
                            $productHoverImageUrl = $productHoverImage->getUrl();
                            $img_ratio = round(($_imagehelper->getHeight() / $_imagehelper->getWidth())*100);
                            ?>
                            <span class="tt-img product-image-container" style="width:<?= /* @escapeNotVerified */ $_imagehelper->getWidth() ?>px;">
                                <span class="product-image-wrapper" style="padding-bottom: <?= /* @escapeNotVerified */ $img_ratio; ?>%;">
                                    <img class="product-image-photo" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                </span>
                            </span>
                            <?php if ($list_conf['list_hover']): ?>
                                <?php if($productImageUrl != str_replace("/img_hover/","/small_image/",$productHoverImageUrl)): ?>
                                    <span class="tt-img-roll-over product-image-container" style="width:<?= /* @escapeNotVerified */ $_imagehelper->getWidth() ?>px;">
                                        <span class="product-image-wrapper" style="padding-bottom: <?= /* @escapeNotVerified */ $img_ratio; ?>%;">
                                            <img class="product-image-photo-hover" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                        </span>
                                    </span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </a>

                        <span class="tt-label-location">
                            <?php if ($list_conf['list_label']): ?>
                                <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->newLabel($_product); ?>
                                <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->saleLabel($_product); ?>
                                <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->featuredLabel($_product); ?>
                                <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->getBestsellers($_product); ?>
                            <?php endif; ?>
                            <?php if (!$_product->isSaleable()): ?>
                                <?php if ($_product->isAvailable()): ?>
                                    <span class="tt-label-out-stock"><?= /* @escapeNotVerified */ __('In stock') ?></span>
                                <?php else: ?>
                                    <span class="tt-label-out-stock"><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </span>
                        <?php
                        if ($list_conf['list_countdown']):
                            echo $this->helper('Ecomwares\Wokiee\Helper\Data')->getCountdown($_product);
                        endif;
                        ?>
                    </div>
                    <div class="tt-description">
                        <div class="tt-row">
                            <?php if ($_product->getAttributeText('manufacturer') && $list_conf['list_brands']): ?>
                                <ul class="tt-add-info">
                                    <li><?php echo $_product->getAttributeText('manufacturer') ?></li>
                                </ul>
                            <?php endif; ?>
                            <?php if ($list_conf['list_rating']): ?>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php endif; ?>
                        </div>
                        <h2 class="tt-title">
                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                        </h2>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <div class="tt-product-inside-hover product actions product-item-actions">
                            <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                            class="tt-btn-addtocart thumbprod-button-bg action tocart primary">
                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            <?php endif; ?>
                            <div class="addto_btns">
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $list_conf['list_wishlist']): ?>
                                    <a href="#"
                                       class="action towishlist"
                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button"></a>
                                <?php endif; ?>
                                <?php if ($list_conf['list_compare']): ?>
                                    <?php /* @escapeNotVerified */ $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                       aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button"></a>
                                <?php endif; ?>
                                <?php if ($list_conf['list_quick'] && $isQuick): ?>
                                    <a href="javascript:void(0);" data-quickview-url="<?= $productUrl; ?>" class="weltpixel-quickview tt-btn-quickview"></a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>


    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>

<?php endif;?>