<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="container-indent">
    <div class="container">
        <div class="tt-block-title">
            <h2 class="tt-title"><?php echo $block->escapeHtml($block->getTitle()) ?></h2>
            <div class="tt-description"><?php echo $block->escapeHtml($block->getSubtitle()) ?></div>
        </div>
        <div class="tt-blog-thumb-list">
            <div class="row">
                <?php foreach ($_postCollection as $_post) : ?>
                    <?php
                    $_postUrl = $_post->getPostUrl();
                    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                    ?>
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                        <div class="tt-blog-thumb">
                            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                            <div class="tt-img">
                                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                                </a>
                            </div>
                            <?php } ?>
                            <div class="tt-title-description">
                                <div class="tt-background"></div>
                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                <div class="tt-tag">
                                    <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                                        <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                        <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                                    <?php } ?>
                                </div>
                                <?php } ?>
                                <div class="tt-title">
                                    <a href="<?php echo $_postUrl ?>"><?php echo $_postName; ?></a>
                                </div>
                                <div class="tt-post-short">
                                    <?php echo $block->getShorContent($_post) ?>
                                </div>
                                <div class="tt-meta">
                                    <div class="tt-autor">
                                        <?php if($_post->getAuthor()!=null):?>
                                            <?php echo __('by') ?> <a href="<?php echo $_post->getAuthor()->getAuthorUrl(); ?>"><?php echo $_post->getAuthor()->getName(); ?></a>
                                        <?php endif;?>
                                        <?php echo __('on') ?> <?php echo $_post->getPublishDate('F d, Y') ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<?php } ?>