<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$list_conf = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('wokiee_settings/product_listing');
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block container-indent <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php else: ?>
            <div class="block container-indent <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block container-indent <?= /* @escapeNotVerified */ $class ?>">
    <?php endif; ?>
    <div class="container container-fluid-custom-mobile-padding">
        <div class="tt-block-title text-left">
            <h3 id="block-<?= /* @escapeNotVerified */ $class ?>-heading" class="tt-title-small">
                <?= /* @escapeNotVerified */ $title ?>
                <?php if ($type == 'related' && $canItemsAddToCart): ?>
                    <span class="block-actions">
                        <?= /* @escapeNotVerified */ __('Check items to add to the cart or') ?>
                        <a href="javascript:void(0);" class="action select" role="select-all"><span><?= /* @escapeNotVerified */ __('select all') ?></span></a>
                    </span>
                <?php endif; ?>
            </h3>
        </div>
        <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
            <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
                <div class="products list items product-items tt-carousel-products row arrow-location-right-top tt-alignment-img tt-layout-product-item slick-animated-show-js">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                    <?php $available = ''; ?>
                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<div class="item product product-item col-2 col-md-4 col-lg-3">' : '</div><div class="item product product-item col-2 col-md-4 col-lg-3">' ?>
                    <div class="product-item-info tt-product thumbprod-center <?= /* @escapeNotVerified */ $available ?>">
                        <div class="tt-image-box">
                            <?php if ($list_conf['list_quick']): ?>
                                <a href="#" class="tt-btn-quickview"></a>
                            <?php endif; ?>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $list_conf['list_wishlist']): ?>
                                <a href="#"
                                   class="action towishlist"
                                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                   aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                   data-action="add-to-wishlist"
                                   role="button"></a>
                            <?php endif; ?>
                            <?php if ($list_conf['list_compare']): ?>
                                <?php /* @escapeNotVerified */ $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                <a href="#"
                                   class="action tocompare"
                                   title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                   aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
                                   role="button"></a>
                            <?php endif; ?>
                            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <span class="tt-label-location">
                                <?php if ($list_conf['list_label']): ?>
                                    <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->newLabel($_item); ?>
                                    <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->saleLabel($_item); ?>
                                    <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->featuredLabel($_item); ?>
                                    <?php echo $this->helper('Ecomwares\Wokiee\Helper\Data')->getBestsellers($_item); ?>
                                <?php endif; ?>
                                    <?php if (!$_item->isSaleable()): ?>
                                        <?php if ($_item->isAvailable()): ?>
                                            <span class="tt-label-out-stock"><?= /* @escapeNotVerified */ __('In stock') ?></span>
                                        <?php else: ?>
                                            <span class="tt-label-out-stock"><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                        <?php endif; ?>
                                    <?php endif; ?>
                            </span>
                            <?php
                            if ($list_conf['list_countdown']):
                                echo $this->helper('Ecomwares\Wokiee\Helper\Data')->getCountdown($_item);
                            endif;
                            ?>
                        </div>
                        <div class="tt-description product details product-item-details">
                            <div class="tt-row">
                                <?php if ($_item->getAttributeText('manufacturer') && $list_conf['list_brands']): ?>
                                    <ul class="tt-add-info">
                                        <li><?php echo $_item->getAttributeText('manufacturer') ?></li>
                                    </ul>
                                <?php endif; ?>
                                <?php if ($list_conf['list_rating']): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                            </div>
                            <h2 class="tt-title">
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" title="<?= $block->escapeHtml($_item->getName()) ?>"><?= $block->escapeHtml($_item->getName()) ?></a>
                            </h2>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>

                                <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <div class="field choice related">
                                            <input type="checkbox" class="checkbox related" id="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>" name="related_products[]" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                            <label class="label" for="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>"><span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span></label>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if ($showAddTo || $showCart): ?>
                                    <div class="tt-product-inside-hover product actions product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="tt-btn-addtocart action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="tt-btn-addtocart thumbprod-button-bg action tocart primary"
                                                                data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ($showAddTo): ?>
                                            <div class="addto_btns">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $list_conf['list_wishlist']): ?>
                                                    <a href="#"
                                                       class="action towishlist"
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button"></a>
                                                <?php endif; ?>
                                                <?php if ($list_conf['list_compare']): ?>
                                                    <?php /* @escapeNotVerified */ $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#"
                                                       class="action tocompare"
                                                       title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                                       aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
                                                       role="button"></a>
                                                <?php endif; ?>
                                                <?php if ($list_conf['list_quick']): ?>
                                                    <a href="#" class="tt-btn-quickview"></a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif;?>
