<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post comments template
 *
 * @var $block \Magefan\Blog\Block\Post\View\Comments
 */
?>
<?php
    $comments = $block->getCommentsCollection();
    $numberOfCommentsToDisplay = $block->getNumberOfComments();
    $session = $block->getCustomerSession();

    $canPost = $block->canPost();
?>
<div id="post-comments">
    <h6 class="tt-title-border"><?php echo __('Leave a reply') ?></h6>
    <!-- reply form -->
    <div class="c-reply cf">
        <?php if ($image = $block->getCustomerImage()) { ?>
        <div class="c-img">
            <img src="<?php echo $image ?>" alt="<?php echo $block->escapeHtml($block->getCustomerName()) ?>">
        </div>
        <?php } ?>
        <div class="form-default c-replyform <?php if ($canPost)  echo 'no-active' ?>">
            <form action="<?php echo $block->getFormUrl() ?>" method="post" data-mage-init='{"validation":{}}'>
                <?php echo $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="post_id" value="<?php echo $block->getPost()->getId() ?>" />
                <?php if ($canPost && !$session->getCustomerGroupId()) { ?>
                <div class="form-group">
                    <label for="inputName" class="control-label"><?php echo __('Full Name') ?> *</label>
                    <input type="text" name="author_nickname" value="" placeholder="<?php echo __('Full Name') ?>" class="form-control input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="control-label"><?php echo __('Email') ?> *</label>
                    <input type="email" name="author_email" autocomplete="email"  value="" placeholder="<?php echo __('Email') ?>" class="form-control input-text" data-validate="{required:true, 'validate-email':true}" aria-required="true">
                </div>
                <?php } ?>
                <div class="form-group">
                    <label for="textarea" class="control-label"><?php echo __('Your comment') ?> *</label>
                    <textarea name="text" class="form-control" rows="8" placeholder="<?php echo $canPost ? __('Add a comment...') : __('Sign in to add a comment...') ?>" <?php if (!$canPost) {?>disabled="disabled"<?php } ?> data-validate="{required:true}"></textarea>
                </div>
                <?php if ($block->displayPrivacyPolicyCheckbox()) { ?>
                <div class="post-agree">
                    <?= $block->getChildBlock('display_privacy_policy_checkbox')->setCommentType('post')->toHtml(); ?>
                </div>
                <?php } ?>
                <div class="form-group">
                    <?php if ($canPost) { ?>
                        <button type="submit" class="btn"><?php echo __('Submit') ?></button>
                    <?php } else { ?>
                        <button type="button" class="btn" onclick="window.location='<?php echo $block->getCustomerUrl()->getLoginUrl() ?>';"><?php echo __('Sign In') ?></button>
                    <?php } ?>
                </div>


            </form>
        </div>
    </div>
<?php
    $commentsCount = count($comments);
    if ($commentsCount) {
?>
    <!-- comments list -->
    <div class="c-comments" >
        <h6 class="tt-title-border"><?php echo __('%1 Comment(s)', $comments->getSize()) ?></h6>
        <?php $i = 0 ?>
        <?php foreach ($comments as $comment) { ?>
            <?php
                $i++;
                $comment->setIsHidden($i > $numberOfCommentsToDisplay);
            ?>
            <?php echo $block->getCommentHtml($comment) ?>
        <?php } ?>
        <?php if ($commentsCount > $numberOfCommentsToDisplay) { ?>
            <a href="#" class="c-allcomments more-comments-action" data-comment="0"><?php echo __('Load more comments') ?></a>
        <?php } ?>
    </div>

    <!-- reply comment form -->
    <div id="c-replyform-comment" class="form-default c-replyform c-replyform-comment" style="display:none">
        <form action="<?php echo $block->getFormUrl() ?>" method="post" data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="post_id" value="<?php echo $block->getPost()->getId() ?>" />
            <input type="hidden" name="parent_id" value="" />
            <?php if ($canPost && !$session->getCustomerGroupId()) { ?>
                <div class="form-group">
                    <label for="inputName" class="control-label"><?php echo __('Full Name') ?> *</label>
                    <input type="text" name="author_nickname" value="" placeholder="<?php echo __('Full Name') ?>" class="form-control input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="control-label"><?php echo __('Email') ?> *</label>
                    <input type="email" name="author_email" autocomplete="email"  value="" placeholder="<?php echo __('Email') ?>" class="form-control input-text" data-validate="{required:true, 'validate-email':true}" aria-required="true">
                </div>
            <?php } ?>
            <div class="form-group">
                <label for="textarea" class="control-label"><?php echo __('Your comment') ?> *</label>
                <textarea name="text" class="form-control" rows="8" placeholder="<?php echo $canPost ? __('Add a comment...') : __('Sign in to add a comment...') ?>" <?php if (!$canPost) {?>disabled="disabled"<?php } ?> data-validate="{required:true}"></textarea>
            </div>
            <?php if ($block->displayPrivacyPolicyCheckbox()) { ?>
                <div class="post-agree">
                    <?= $block->getChildBlock('display_privacy_policy_checkbox')->setCommentType('post')->toHtml(); ?>
                </div>
            <?php } ?>
            <div class="form-group">
                <?php if ($canPost) { ?>
                    <button type="submit" class="btn"><?php echo __('Submit') ?></button>
                <?php } else { ?>
                    <button type="button" class="btn" onclick="window.location='<?php echo $block->getCustomerUrl()->getLoginUrl() ?>';"><?php echo __('Sign In') ?></button>
                <?php } ?>
                <button type="button" class="btn cancel reply-cancel-action" ><?php echo __('Cancel') ?></button>
            </div>

        </form>
    </div>
<?php } ?>
</div>

<script type="text/x-magento-init">
{
    "#post-comments": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout() ?>
    }
}
</script>
