<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="tt-cart tt-dropdown-obj minicart-wrapper">
    <button class="tt-dropdown-toggle" data-bind="scope: 'minicart_content'">
        <i class="icon-f-39"></i>
        <span class="tt-badge-cart counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <!-- ko if: getCartParam('summary_count') -->
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <!-- /ko -->
            <!-- ko ifnot: getCartParam('summary_count') -->
            <span class="counter-number">0</span>
            <!-- /ko -->
        </span>
    </button>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="tt-dropdown-menu">
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
        }
    }
    </script>
</div>


