<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$collapsible = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('wokiee_settings/sidebar/collapsible');
$opened = $this->helper('Ecomwares\Wokiee\Helper\Data')->getSystemValue('wokiee_settings/sidebar/opened');
if ($collapsible) {
    $c_class = ' collapsible';
} else {
    $c_class = '';
}
if ($collapsible && $opened) {
    $o_class = ' open';
} else {
    $o_class = '';
}
?>

<div class="block<?= $c_class.$o_class; ?> <?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
    <div class="block-title <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-title">
        <strong><?= /* @escapeNotVerified */ $block->getBlockTitle() ?></strong>
    </div>
    <div class="block-content <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-content" id="<?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
        <?= $block->getChildHtml() ?>
    </div>
</div>
