<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
    <?php if ($this->getRequest()->getFullActionName() == 'catalog_product_view'): ?>
        <h1 class="tt-title"><?= /* @escapeNotVerified */ $title ?></h1>
    <?php else: ?>
        <div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
            <h1 class="tt-title-subpages noborder"
                <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
                <?php if ($block->getAddBaseAttributeAria()): ?>
                    aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
                <?php endif; ?>>
                <?= /* @escapeNotVerified */ $title ?>
            </h1>
            <?= $block->getChildHtml() ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
