<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="tt-post-single">
    <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
        <div class="tt-tag">
            <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
            <?php } ?>
        </div>
    <?php } ?>
    <h1 class="tt-title">
        <?php echo $_postName ?>
    </h1>
    <div class="tt-autor">
        <?php if($_post->getAuthor()!=null):?>
            <?php echo __('by') ?> <a href="<?php echo $_post->getAuthor()->getAuthorUrl(); ?>"><?php echo $_post->getAuthor()->getName(); ?></a>
        <?php endif;?>
        <?php echo __('on') ?> <?php echo $_post->getPublishDate('F d, Y') ?>
    </div>
    <div class="tt-post-content">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
        <?php } ?>
        <div class="tt-post-text">
            <?php echo $block->getContent() ?>
        </div>
    </div>
    <div class="post-meta-wrap">
        <?php if ($_tagsCount = $_post->getTagsCount()) { ?>
            <div class="post-meta">
            <span class="item">
                <span><?php echo __('Tags:') ?></span>
                <?php $n = 0; foreach($_post->getRelatedTags() as $tag) { $n++; ?>
                    <span><a title="<?php echo $block->escapeHtml($tag->getTitle()) ?>" href="<?php echo $tag->getTagUrl() ?>">
                            <?php echo $block->escapeHtml($tag->getTitle()) ?>
                        </a></span>
                    <?php if ($n != $_tagsCount) { ?>, <?php } ?>
                <?php } ?>
            </span>
            </div>
        <?php } ?>
        <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_email"></a>
            <a class="addthis_button_compact"></a>
        </div>
    </div>

    <div class="post-bottom">
        <?php echo $this->getChildHtml('blog.post.bottom') ?>
    </div>

</div>