<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<?php
/* */
$ys_helper = $this->helper('Ecomwares\Wokiee\Helper\Data');
$media_url = $ys_helper->getMediaUrl();

$contact_static = $ys_helper->getSystemValue('wokiee_settings/contacts/contact_static');
$static_id = $ys_helper->getSystemValue('wokiee_settings/contacts/static_id');
$google_map = $ys_helper->getSystemValue('wokiee_settings/contacts/google_map');
$gm_api = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_api');
$gm_coordinates = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_coordinates');
$gm_zoom = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_zoom');
$gm_scrollwheel = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_scrollwheel');
$gm_draggable = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_draggable');
$gm_ui = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_ui');
$gm_styles = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_styles');
$gm_marker_title = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_marker_title');
$gm_marker_coordinates = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_marker_coordinates');
$gm_marker_img = $ys_helper->getSystemValue('wokiee_settings/contacts/gm_marker_img');

$html=$this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($static_id)->toHtml();
?>

<?php if ($google_map): ?>
    <script src="https://maps.googleapis.com/maps/api/js?<?php if($gm_api) { echo 'key='.$gm_api.'&'; } ?>sensor=false" type="text/javascript" xml="space"></script>
    <!-- map -->
    <section class="contact-map">
        <div id="map"></div>
    </section>
    <!-- /map -->

    <script>
        require([
            'jquery'
        ], function ($) {

            // When the window has finished loading create our google map below
            google.maps.event.addDomListener(window, 'load', init);

            function init() {
                // Basic options for a simple Google Map
                // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
                var mapOptions = {
                    // How zoomed in you want the map to start at (always required)
                    <?php if($gm_zoom): ?>
                    zoom: <?php echo $gm_zoom; ?>,
                    <?php endif; ?>

                    // The latitude and longitude to center the map (always required)
                    center: new google.maps.LatLng(<?php echo $gm_coordinates; ?>), // New York

                    scrollwheel:  <?php echo $gm_scrollwheel; ?>,
                    draggable:  <?php echo $gm_draggable; ?>,
                    disableDefaultUI:  <?php echo $gm_ui; ?>,

                    // How you would like to style the map.
                    // This is where you would paste any style found on Snazzy Maps.
                    <?php if($gm_styles): ?>
                    styles: <?php echo $gm_styles; ?>
                    <?php endif; ?>
                };

                // Get the HTML DOM element that will contain your map
                // We are using a div with id="map" seen below in the <body>
                var mapElement = document.getElementById('map');

                // Create the Google Map using our element and options defined above
                var map = new google.maps.Map(mapElement, mapOptions);

                var image = '<?php echo $media_url; ?>marker/<?php echo $gm_marker_img; ?>';

                var marker = new google.maps.Marker({
                    position: new google.maps.LatLng(<?php echo $gm_marker_coordinates; ?>),
                    map: map,
                    <?php if($gm_marker_img): ?>
                    icon : image,
                    <?php endif; ?>
                    <?php if($gm_marker_title): ?>
                    title: '<?php echo $gm_marker_title; ?>'
                    <?php endif; ?>
                });
            }

        });
    </script>
<?php endif; ?>

<?php if ($contact_static):
    if($html!=''):
        echo $html;
    endif;
endif; ?>

<form class="form contact-us-form"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?></div>
        <div class="row">
            <div class="col-md-6">
                <div class="field name required">
                    <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field telephone">
                    <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="field comment required">
                    <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                    </div>
                </div>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="text-center">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
