<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="block related comments-single-post">
        <h6 class="tt-title-border"><?php echo __('Related Posts') ?></h6>
        <div class="tt-blog-thumb-list">
            <div class="row">
                <?php foreach ($_postCollection as $_post) { ?>
                    <div class="col-sm-6">
                        <div class="tt-blog-thumb">
                            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                            <div class="tt-img">
                                <a href="<?php echo $_post->getPostUrl() ?>">
                                    <img src="<?php echo $featuredImage ?>" />
                                </a>
                            </div>
                            <?php } ?>
                            <div class="tt-title-description">
                                <div class="tt-background"></div>
                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <div class="tt-tag">
                                        <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                                            <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                            <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                <div class="tt-title">
                                    <a href="<?php echo $_post->getPostUrl() ?>">
                                        <?php echo $block->escapeHtml($_post->getTitle()); ?>
                                    </a>
                                </div>
                            </div>
                        </div>


                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php } ?>
<?php } ?>